In [1]:
#AI建立一個function
#資料來源:scores = np.random.randint(50,101,size=(50, 5))
#欄位: ['國文', '英文', '數學', '自然', '社會','總分','平均','排名']
#索引: ['學生' + str(i) for i in range(1, 51)]
#建立DataFrame
import numpy as np
import pandas as pd 

def build_scores_dataframe(scores):
    df = pd.DataFrame(scores,
                      columns=['國文', '英文', '數學', '自然', '社會'],
                      index=['學生' + str(i) for i in range(1, 51)])
    df.index.name = '學生'
    df.columns.name = '科目'
    sum_values = df.sum(axis=1)
    mean_values = df.mean(axis=1)
    df['總分'] = sum_values
    df['平均'] = mean_values
    rank_values = sum_values.rank(method='min', ascending=False)
    df['排名'] = rank_values
    return df

scores = np.random.randint(50,101,size=(50, 5))
df = build_scores_dataframe(scores)
df

科目    國文   英文   數學   自然   社會   總分    平均    排名
學生
學生1   87   89   66   63   59  364  72.8  32.0
學生2   53   97   63   99   84  396  79.2  10.0
學生3   94   65   84   71   50  364  72.8  32.0
學生4   91   69   70   70   98  398  79.6   9.0
學生5   65   83   63  100   68  379  75.8  16.0
學生6   82   78   66   74   69  369  73.8  29.0
學生7   75   88   55   77   55  350  70.0  41.0
學生8   67   85   62   61   64  339  67.8  45.0
學生9   80   53   73   56   84  346  69.2  43.0
學生10  97   66   73   75   59  370  74.0  27.0
學生11  91   77   81   53   74  376  75.2  21.0
學生12  95   65   91   76   54  381  76.2  15.0
學生13  87  100   98   74   81  440  88.0   2.0
學生14  56   51   76  100   94  377  75.4  20.0
學生15  67   62   72   86   91  378  75.6  18.0
學生16  92   66  100   62   65  385  77.0  12.0
學生17  88   80   86   67   84  405  81.0   7.0
學生18  74   59   73   89   60  355  71.0  40.0
學生19  52   70   60   98   98  378  75.6  18.0
學生20  68   74   56   83   93  374  74.8  22.0
學生21  76   52   51   99   89  367  73.4  30.0
學生22  70   73   53   91   85  372  74.4  24.0
學生23  76   54   54   90  100  374  74.8  22.0
學生24  63   58   57   88   58  324  64.8  49.0
學生25  97   53   50   69   57  326  65.2  48.0
學生26  91   53   94   70   71  379  75.8  16.0
學生27  54   88   54   80   89  365  73.0  31.0
學生28  64   79   67   89  100  399  79.8   8.0
學生29  52   82   96   76   78  384  76.8  13.0
學生30  84   67   98   77   96  422  84.4   4.0
學生31  86  100   54   87   57  384  76.8  13.0
學生32  96   95   89   71   95  446  89.2   1.0
學生33  92   73   54   97   98  414  82.8   6.0
學生34  56   55   50   60   93  314  62.8  50.0
學生35  74   63   76   64   95  372  74.4  24.0
學生36  55   83   63   86   69  356  71.2  39.0
學生37  99   59   88   67   83  396  79.2  10.0
學生38  64   87   75   85   61  372  74.4  24.0
學生39  74   62   58   98   78  370  74.0  27.0
學生40  61   70   80   79   69  359  71.8  35.0
學生41  66   67   75   57   72  337  67.4  47.0
學生42  98   79   85   77   80  419  83.8   5.0
學生43  95   55   70   75   52  347  69.4  42.0
學生44  76   58   90   53   80  357  71.4  37.0
學生45  94   90   67   60   52  363  72.6  34.0
學生46  63   83   58   72   81  357  71.4  37.0
學生47  76   84   84   93   93  430  86.0   3.0
學生48  68   71   70   66   68  343  68.6  44.0
學生49  98   74   65   60   61  358  71.6  36.0
學生50  68   67   77   65   61  338  67.6  46.0

In [2]:
#選擇欄位
df1 = df[['國文', '英文', '數學', '自然', '社會']]
df1

科目    國文   英文   數學   自然   社會
學生
學生1   87   89   66   63   59
學生2   53   97   63   99   84
學生3   94   65   84   71   50
學生4   91   69   70   70   98
學生5   65   83   63  100   68
學生6   82   78   66   74   69
學生7   75   88   55   77   55
學生8   67   85   62   61   64
學生9   80   53   73   56   84
學生10  97   66   73   75   59
學生11  91   77   81   53   74
學生12  95   65   91   76   54
學生13  87  100   98   74   81
學生14  56   51   76  100   94
學生15  67   62   72   86   91
學生16  92   66  100   62   65
學生17  88   80   86   67   84
學生18  74   59   73   89   60
學生19  52   70   60   98   98
學生20  68   74   56   83   93
學生21  76   52   51   99   89
學生22  70   73   53   91   85
學生23  76   54   54   90  100
學生24  63   58   57   88   58
學生25  97   53   50   69   57
學生26  91   53   94   70   71
學生27  54   88   54   80   89
學生28  64   79   67   89  100
學生29  52   82   96   76   78
學生30  84   67   98   77   96
學生31  86  100   54   87   57
學生32  96   95   89   71   95
學生33  92   73   54   97   98
學生34  56   55   50   60   93
學生35  74   63   76   64   95
學生36  55   83   63   86   69
學生37  99   59   88   67   83
學生38  64   87   75   85   61
學生39  74   62   58   98   78
學生40  61   70   80   79   69
學生41  66   67   75   57   72
學生42  98   79   85   77   80
學生43  95   55   70   75   52
學生44  76   58   90   53   80
學生45  94   90   67   60   52
學生46  63   83   58   72   81
學生47  76   84   84   93   93
學生48  68   71   70   66   68
學生49  98   74   65   60   61
學生50  68   67   77   65   61

In [ ]:
s = df1.loc['學生1'] #取出學生1的分數
less_than_60_series = s[s<60]
#取出不及格的科目
failing_subjects = less_than_60_series.index.tolist()
failing_subjects
#取出不及格科目的分數
failing_scores = less_than_60_series.tolist()
failing_scores
#建立一個Series,值要轉換為字串,如果有多個值則用逗號分隔
failing_scores_str = ','.join(map(str, failing_scores))
failing_subjects_str = ','.join(failing_subjects)
pd.Series([failing_scores_str, failing_subjects_str], index=['分數', '不及格科目'])

分數       59
不及格科目    社會
dtype: object

In [12]:
def apply_statistics(s):
    less_than_60_series = s[s<60]
    #不及格科目數量
    failing_subjects_count = less_than_60_series.count()
    #取出不及格的科目
    failing_subjects = less_than_60_series.index.tolist()
    
    #取出不及格科目的分數
    failing_scores = less_than_60_series.tolist()
    
    #建立一個Series,值要轉換為字串,如果有多個值則用逗號分隔
    failing_scores_str = ','.join(map(str, failing_scores))
    failing_subjects_str = ','.join(failing_subjects)
    return pd.Series([failing_subjects_count,failing_subjects_str,failing_scores_str], index=['不及格科目數量', '不及格科目', '分數'])


df2 = df1.apply(apply_statistics, axis=1)
df2

      不及格科目數量     不及格科目        分數
學生
學生1         1        社會        59
學生2         1        國文        53
學生3         1        社會        50
學生4         0
學生5         0
學生6         0
學生7         2     數學,社會     55,55
學生8         0
學生9         2     英文,自然     53,56
學生10        1        社會        59
學生11        1        自然        53
學生12        1        社會        54
學生13        0
學生14        2     國文,英文     56,51
學生15        0
學生16        0
學生17        0
學生18        1        英文        59
學生19        1        國文        52
學生20        1        數學        56
學生21        2     英文,數學     52,51
學生22        1        數學        53
學生23        2     英文,數學     54,54
學生24        3  英文,數學,社會  58,57,58
學生25        3  英文,數學,社會  53,50,57
學生26        1        英文        53
學生27        2     國文,數學     54,54
學生28        0
學生29        1        國文        52
學生30        0
學生31        2     數學,社會     54,57
學生32        0
學生33        1        數學        54
學生34        3  國文,英文,數學  56,55,50
學生35        0
學生36        1        國文        55
學生37        1        英文        59
學生38        0
學生39        1        數學        58
學生40        0
學生41        1        自然        57
學生42        0
學生43        2     英文,社會     55,52
學生44        2     英文,自然     58,53
學生45        1        社會        52
學生46        1        數學        58
學生47        0
學生48        0
學生49        0
學生50        0

In [13]:
#df要和df2合併
df_merged = pd.concat([df, df2], axis=1)
df_merged

      國文   英文   數學   自然   社會   總分    平均    排名  不及格科目數量     不及格科目        分數
學生
學生1   87   89   66   63   59  364  72.8  32.0        1        社會        59
學生2   53   97   63   99   84  396  79.2  10.0        1        國文        53
學生3   94   65   84   71   50  364  72.8  32.0        1        社會        50
學生4   91   69   70   70   98  398  79.6   9.0        0
學生5   65   83   63  100   68  379  75.8  16.0        0
學生6   82   78   66   74   69  369  73.8  29.0        0
學生7   75   88   55   77   55  350  70.0  41.0        2     數學,社會     55,55
學生8   67   85   62   61   64  339  67.8  45.0        0
學生9   80   53   73   56   84  346  69.2  43.0        2     英文,自然     53,56
學生10  97   66   73   75   59  370  74.0  27.0        1        社會        59
學生11  91   77   81   53   74  376  75.2  21.0        1        自然        53
學生12  95   65   91   76   54  381  76.2  15.0        1        社會        54
學生13  87  100   98   74   81  440  88.0   2.0        0
學生14  56   51   76  100   94  377  75.4  20.0        2     國文,英文     56,51
學生15  67   62   72   86   91  378  75.6  18.0        0
學生16  92   66  100   62   65  385  77.0  12.0        0
學生17  88   80   86   67   84  405  81.0   7.0        0
學生18  74   59   73   89   60  355  71.0  40.0        1        英文        59
學生19  52   70   60   98   98  378  75.6  18.0        1        國文        52
學生20  68   74   56   83   93  374  74.8  22.0        1        數學        56
學生21  76   52   51   99   89  367  73.4  30.0        2     英文,數學     52,51
學生22  70   73   53   91   85  372  74.4  24.0        1        數學        53
學生23  76   54   54   90  100  374  74.8  22.0        2     英文,數學     54,54
學生24  63   58   57   88   58  324  64.8  49.0        3  英文,數學,社會  58,57,58
學生25  97   53   50   69   57  326  65.2  48.0        3  英文,數學,社會  53,50,57
學生26  91   53   94   70   71  379  75.8  16.0        1        英文        53
學生27  54   88   54   80   89  365  73.0  31.0        2     國文,數學     54,54
學生28  64   79   67   89  100  399  79.8   8.0        0
學生29  52   82   96   76   78  384  76.8  13.0        1        國文        52
學生30  84   67   98   77   96  422  84.4   4.0        0
學生31  86  100   54   87   57  384  76.8  13.0        2     數學,社會     54,57
學生32  96   95   89   71   95  446  89.2   1.0        0
學生33  92   73   54   97   98  414  82.8   6.0        1        數學        54
學生34  56   55   50   60   93  314  62.8  50.0        3  國文,英文,數學  56,55,50
學生35  74   63   76   64   95  372  74.4  24.0        0
學生36  55   83   63   86   69  356  71.2  39.0        1        國文        55
學生37  99   59   88   67   83  396  79.2  10.0        1        英文        59
學生38  64   87   75   85   61  372  74.4  24.0        0
學生39  74   62   58   98   78  370  74.0  27.0        1        數學        58
學生40  61   70   80   79   69  359  71.8  35.0        0
學生41  66   67   75   57   72  337  67.4  47.0        1        自然        57
學生42  98   79   85   77   80  419  83.8   5.0        0
學生43  95   55   70   75   52  347  69.4  42.0        2     英文,社會     55,52
學生44  76   58   90   53   80  357  71.4  37.0        2     英文,自然     58,53
學生45  94   90   67   60   52  363  72.6  34.0        1        社會        52
學生46  63   83   58   72   81  357  71.4  37.0        1        數學        58
學生47  76   84   84   93   93  430  86.0   3.0        0
學生48  68   71   70   66   68  343  68.6  44.0        0
學生49  98   74   65   60   61  358  71.6  36.0        0
學生50  68   67   77   65   61  338  67.6  46.0        0

In [14]:
#df_merged請儲存為excel檔
df_merged.to_excel('df_merged.xlsx')