In [8]:
#AI建立一個function
#資料來源:scores = np.random.randint(50,101,size=(50, 5))
#欄位: ['國文', '英文', '數學', '自然', '社會', '總分', '平均', '排名']
#索引:['學生' + str(i) for i in range(1, 51)]
#建立DataFrame

import numpy as np
import pandas as pd 
def create_dataframe(scores):
    scores = np.random.randint(50,101,size=(50, 5))
    df = pd.DataFrame(scores,
                      columns=['國文', '英文', '數學', '自然', '社會'],
                      index=['學生' + str(i) for i in range(1, 51)])
    df.index.name = '學生' #設定索引名稱
    df.columns.name = '科目' #設定列名稱
    sum_values = df.sum(axis=1) #加總columns
    mean_values = df.mean(axis=1) #平均columns
    df['總分'] = sum_values #加入總分列
    df['平均'] = mean_values #加入平均列
    rank_values = sum_values.rank(method='min', ascending=False )
    df['排名'] = rank_values
    return df

In [9]:
scores = np.random.randint(50,101,size=(50, 5))
df = create_dataframe(scores)
df

科目    國文   英文  數學  自然   社會   總分    平均    排名
學生
學生1   78   59  95  59  100  391  78.2  13.0
學生2   90   54  98  90   55  387  77.4  17.0
學生3   53   92  71  62   58  336  67.2  42.0
學生4   59   84  76  55   98  372  74.4  23.0
學生5   80   69  68  65   66  348  69.6  36.0
學生6   97   61  56  69   50  333  66.6  43.0
學生7   66   98  91  73   75  403  80.6  10.0
學生8   82   62  53  50   75  322  64.4  47.0
學生9   54   96  59  81  100  390  78.0  15.0
學生10  68   99  95  70   75  407  81.4   9.0
學生11  77   86  67  67   71  368  73.6  27.0
學生12  54   91  85  99   96  425  85.0   5.0
學生13  78   99  71  94   93  435  87.0   3.0
學生14  95   77  90  54   85  401  80.2  11.0
學生15  82   93  98  92   79  444  88.8   2.0
學生16  79   83  90  58   82  392  78.4  12.0
學生17  51   66  58  75   68  318  63.6  48.0
學生18  65   57  78  64   83  347  69.4  37.0
學生19  89   60  92  77   55  373  74.6  21.0
學生20  66   65  89  78   52  350  70.0  34.0
學生21  74  100  71  80   92  417  83.4   6.0
學生22  83   68  88  54   82  375  75.0  20.0
學生23  67   60  89  63   90  369  73.8  25.0
學生24  69   74  96  86   61  386  77.2  18.0
學生25  79   89  79  95   72  414  82.8   7.0
學生26  83   52  67  63   51  316  63.2  49.0
學生27  64   51  79  77   79  350  70.0  34.0
學生28  67   74  76  59   89  365  73.0  29.0
學生29  85   84  96  54   50  369  73.8  25.0
學生30  73   67  92  88   88  408  81.6   8.0
學生31  79   95  82  71   64  391  78.2  13.0
學生32  63   86  99  54   50  352  70.4  33.0
學生33  88   87  59  71   67  372  74.4  23.0
學生34  97   69  53  71   83  373  74.6  21.0
學生35  51   52  98  71   52  324  64.8  46.0
學生36  85   61  55  64   50  315  63.0  50.0
學生37  85   55  80  50   88  358  71.6  31.0
學生38  98   58  67  59   56  338  67.6  41.0
學生39  58   70  98  72   79  377  75.4  19.0
學生40  60   59  75  54   85  333  66.6  43.0
學生41  61   50  80  63   92  346  69.2  38.0
學生42  62   72  81  82   92  389  77.8  16.0
學生43  67   51  55  86   68  327  65.4  45.0
學生44  98   84  91  93   91  457  91.4   1.0
學生45  84   99  64  99   84  430  86.0   4.0
學生46  77   79  51  74   75  356  71.2  32.0
學生47  63   75  82  56   83  359  71.8  30.0
學生48  55   73  90  64   61  343  68.6  39.0
學生49  50   55  92  81   89  367  73.4  28.0
學生50  85   57  71  76   50  339  67.8  40.0

In [16]:
#AI建立1個統計的DataFrame
#欄位為: ['國文', '英文', '數學', '自然', '社會']
#索引為: ['平均', '最高', '最低', '中間值']
def create_statistics_dataframe(df):
    cols = ['國文', '英文', '數學', '自然', '社會']
    stats = df[cols].agg(['mean', 'max', 'min', 'median'])
    stats.index = ['平均', '最高', '最低', '中間值']
    return stats
create_statistics_dataframe(df)

科目      國文      英文     數學     自然      社會
平均   73.46   73.14  78.72  71.24   74.58
最高   98.00  100.00  99.00  99.00  100.00
最低   50.00   50.00  51.00  50.00   50.00
中間值  75.50   71.00  80.00  71.00   77.00