In [1]:
import numpy as np
import pandas as pd
df = pd.DataFrame(np.arange(16).reshape(4,4),
                   index=['台北','台中', '台南', '高雄'],
                   columns=['one', 'two', 'three', 'four'])
df

    one  two  three  four
台北    0    1      2     3
台中    4    5      6     7
台南    8    9     10    11
高雄   12   13     14    15

In [2]:
#drop是用來刪除行或列的方法
df.drop(index=['台北', '高雄'], inplace=True) #inplace是指在原始物件上進行修改
df

    one  two  three  four
台中    4    5      6     7
台南    8    9     10    11

In [ ]:
#排序和排名

scores = np.random.randint(50,101,size=(50, 5))
df = pd.DataFrame(scores,
                  columns=['國文', '英文', '數學', '自然', '社會'],
                  index=['學生' + str(i) for i in range(1, 51)])
df.index.name = '學生' #設定索引名稱
df.columns.name = '科目' #設定列名稱
sum_values = df.sum(axis=1) #加總columns
mean_values = df.mean(axis=1) #平均columns
df['總分'] = sum_values #加入總分列
df['平均'] = mean_values #加入平均列
df

科目     國文   英文  數學  自然  社會   總分    平均
學生
學生1    85   67  88  71  79  390  78.0
學生2    68   68  52  59  68  315  63.0
學生3    77   56  53  90  98  374  74.8
學生4    75   54  88  97  67  381  76.2
學生5    98   89  62  76  53  378  75.6
學生6    85   64  88  68  93  398  79.6
學生7    88   96  85  61  83  413  82.6
學生8    88   77  85  83  61  394  78.8
學生9    88   88  94  79  61  410  82.0
學生10   76   66  77  53  73  345  69.0
學生11   78   97  77  94  90  436  87.2
學生12   80   79  99  63  95  416  83.2
學生13   98   67  52  92  60  369  73.8
學生14   75   98  99  69  84  425  85.0
學生15   55   77  91  92  60  375  75.0
學生16   90   96  78  86  88  438  87.6
學生17   95   86  68  73  94  416  83.2
學生18   81   70  99  85  97  432  86.4
學生19   57   53  62  79  52  303  60.6
學生20   58   56  70  51  72  307  61.4
學生21   69   84  79  63  84  379  75.8
學生22   61   80  69  75  93  378  75.6
學生23  100   63  71  89  52  375  75.0
學生24   72   80  52  51  80  335  67.0
學生25   72   61  72  50  83  338  67.6
學生26   66   53  83  74  92  368  73.6
學生27   84   58  83  55  64  344  68.8
學生28   96   98  56  95  73  418  83.6
學生29   83   55  72  50  80  340  68.0
學生30   94   55  80  99  88  416  83.2
學生31   89   99  73  91  86  438  87.6
學生32   97   75  82  62  91  407  81.4
學生33   92   89  53  85  75  394  78.8
學生34   62   77  58  64  77  338  67.6
學生35   52   82  57  78  74  343  68.6
學生36   67   54  66  97  59  343  68.6
學生37   57   81  80  56  74  348  69.6
學生38   98   71  51  82  53  355  71.0
學生39   55   55  68  93  57  328  65.6
學生40   67   95  68  52  93  375  75.0
學生41   77   92  96  96  71  432  86.4
學生42   68  100  79  70  58  375  75.0
學生43   62   57  95  93  69  376  75.2
學生44   66   55  72  97  62  352  70.4
學生45   50   72  57  61  75  315  63.0
學生46   93   87  71  60  95  406  81.2
學生47   63   95  70  53  75  356  71.2
學生48   58   61  53  77  87  336  67.2
學生49   80   82  79  51  84  376  75.2
學生50   59   86  58  76  86  365  73.0

In [6]:
#排序和排名
#rank()
rank_values = sum_values.rank(method='min', ascending=False )
df['排名'] = rank_values
df

科目     國文   英文  數學  自然  社會   總分    平均    排名
學生
學生1    85   67  88  71  79  390  78.0  18.0
學生2    68   68  52  59  68  315  63.0  47.0
學生3    77   56  53  90  98  374  74.8  29.0
學生4    75   54  88  97  67  381  76.2  19.0
學生5    98   89  62  76  53  378  75.6  21.0
學生6    85   64  88  68  93  398  79.6  15.0
學生7    88   96  85  61  83  413  82.6  11.0
學生8    88   77  85  83  61  394  78.8  16.0
學生9    88   88  94  79  61  410  82.0  12.0
學生10   76   66  77  53  73  345  69.0  37.0
學生11   78   97  77  94  90  436  87.2   3.0
學生12   80   79  99  63  95  416  83.2   8.0
學生13   98   67  52  92  60  369  73.8  30.0
學生14   75   98  99  69  84  425  85.0   6.0
學生15   55   77  91  92  60  375  75.0  25.0
學生16   90   96  78  86  88  438  87.6   1.0
學生17   95   86  68  73  94  416  83.2   8.0
學生18   81   70  99  85  97  432  86.4   4.0
學生19   57   53  62  79  52  303  60.6  50.0
學生20   58   56  70  51  72  307  61.4  49.0
學生21   69   84  79  63  84  379  75.8  20.0
學生22   61   80  69  75  93  378  75.6  21.0
學生23  100   63  71  89  52  375  75.0  25.0
學生24   72   80  52  51  80  335  67.0  45.0
學生25   72   61  72  50  83  338  67.6  42.0
學生26   66   53  83  74  92  368  73.6  31.0
學生27   84   58  83  55  64  344  68.8  38.0
學生28   96   98  56  95  73  418  83.6   7.0
學生29   83   55  72  50  80  340  68.0  41.0
學生30   94   55  80  99  88  416  83.2   8.0
學生31   89   99  73  91  86  438  87.6   1.0
學生32   97   75  82  62  91  407  81.4  13.0
學生33   92   89  53  85  75  394  78.8  16.0
學生34   62   77  58  64  77  338  67.6  42.0
學生35   52   82  57  78  74  343  68.6  39.0
學生36   67   54  66  97  59  343  68.6  39.0
學生37   57   81  80  56  74  348  69.6  36.0
學生38   98   71  51  82  53  355  71.0  34.0
學生39   55   55  68  93  57  328  65.6  46.0
學生40   67   95  68  52  93  375  75.0  25.0
學生41   77   92  96  96  71  432  86.4   4.0
學生42   68  100  79  70  58  375  75.0  25.0
學生43   62   57  95  93  69  376  75.2  23.0
學生44   66   55  72  97  62  352  70.4  35.0
學生45   50   72  57  61  75  315  63.0  47.0
學生46   93   87  71  60  95  406  81.2  14.0
學生47   63   95  70  53  75  356  71.2  33.0
學生48   58   61  53  77  87  336  67.2  44.0
學生49   80   82  79  51  84  376  75.2  23.0
學生50   59   86  58  76  86  365  73.0  32.0

In [ ]:
#sort_values()是用來根據值排序的函數
#sort_index()是用來根據索引排序的函數
df1 = df.sort_values(by='總分', ascending=False)
df1

科目     國文   英文  數學  自然  社會   總分    平均    排名
學生
學生16   90   96  78  86  88  438  87.6   1.0
學生31   89   99  73  91  86  438  87.6   1.0
學生11   78   97  77  94  90  436  87.2   3.0
學生18   81   70  99  85  97  432  86.4   4.0
學生41   77   92  96  96  71  432  86.4   4.0
學生14   75   98  99  69  84  425  85.0   6.0
學生28   96   98  56  95  73  418  83.6   7.0
學生30   94   55  80  99  88  416  83.2   8.0
學生12   80   79  99  63  95  416  83.2   8.0
學生17   95   86  68  73  94  416  83.2   8.0
學生7    88   96  85  61  83  413  82.6  11.0
學生9    88   88  94  79  61  410  82.0  12.0
學生32   97   75  82  62  91  407  81.4  13.0
學生46   93   87  71  60  95  406  81.2  14.0
學生6    85   64  88  68  93  398  79.6  15.0
學生33   92   89  53  85  75  394  78.8  16.0
學生8    88   77  85  83  61  394  78.8  16.0
學生1    85   67  88  71  79  390  78.0  18.0
學生4    75   54  88  97  67  381  76.2  19.0
學生21   69   84  79  63  84  379  75.8  20.0
學生22   61   80  69  75  93  378  75.6  21.0
學生5    98   89  62  76  53  378  75.6  21.0
學生49   80   82  79  51  84  376  75.2  23.0
學生43   62   57  95  93  69  376  75.2  23.0
學生15   55   77  91  92  60  375  75.0  25.0
學生42   68  100  79  70  58  375  75.0  25.0
學生40   67   95  68  52  93  375  75.0  25.0
學生23  100   63  71  89  52  375  75.0  25.0
學生3    77   56  53  90  98  374  74.8  29.0
學生13   98   67  52  92  60  369  73.8  30.0
學生26   66   53  83  74  92  368  73.6  31.0
學生50   59   86  58  76  86  365  73.0  32.0
學生47   63   95  70  53  75  356  71.2  33.0
學生38   98   71  51  82  53  355  71.0  34.0
學生44   66   55  72  97  62  352  70.4  35.0
學生37   57   81  80  56  74  348  69.6  36.0
學生10   76   66  77  53  73  345  69.0  37.0
學生27   84   58  83  55  64  344  68.8  38.0
學生35   52   82  57  78  74  343  68.6  39.0
學生36   67   54  66  97  59  343  68.6  39.0
學生29   83   55  72  50  80  340  68.0  41.0
學生25   72   61  72  50  83  338  67.6  42.0
學生34   62   77  58  64  77  338  67.6  42.0
學生48   58   61  53  77  87  336  67.2  44.0
學生24   72   80  52  51  80  335  67.0  45.0
學生39   55   55  68  93  57  328  65.6  46.0
學生2    68   68  52  59  68  315  63.0  47.0
學生45   50   72  57  61  75  315  63.0  47.0
學生20   58   56  70  51  72  307  61.4  49.0
學生19   57   53  62  79  52  303  60.6  50.0